#!/bin/bash
clear
RED='\033[1;31m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
CYAN='\033[1;36m'
CORTITLE='\033[1;41m'
DIR='/etc/SSHPlus/dns'
SCOLOR='\033[0m'

configdns() {
    interface=$(ip a | awk '/state UP/{print $2}' | cut -d: -f1)
    iptables -F >/dev/null 2>&1
    iptables -I INPUT -p udp --dport 5300 -j ACCEPT
    iptables -t nat -I PREROUTING -i $interface -p udp --dport 53 -j REDIRECT --to-ports 5300
    ip6tables -I INPUT -p udp --dport 5300 -j ACCEPT
    ip6tables -t nat -I PREROUTING -i $interface -p udp --dport 53 -j REDIRECT --to-ports 5300
}

echo -e "${CORTITLE}           SSHPLUS SLOWDNS (Beta)            ${SCOLOR}"
installslowdns() {
    echo -e "\n${YELLOW}TENGA EN CUENTA QUE ESTE METODO AUN\nESTA EN FASE BETA Y QUE ADEMAS DE SER\nLENO PUEDE NO FUNCIONAR PERFECTAMENTE! ${SCOLOR}\n"
    echo -ne "${GREEN}DESEA CONTINUAR LA INSTALACION? ${YELLOW}[s/n]:${SCOLOR} "
    read resp
    [[ "$resp" != @(s|S) ]] && {
        echo -e "\n${RED}Volviendo...${SCOLOR}"
        sleep 2
        menu
    }
    mkdir /etc/SSHPlus/dns >/dev/null 2>&1
    wget -P $DIR https://github.com/Netxxus/SSHPLUS/raw/main/Install/dns-server >/dev/null 2>&1
    chmod 777 $DIR/dns-server >/dev/null 2>&1
    $DIR/dns-server -gen-key -privkey-file $DIR/server.key -pubkey-file $DIR/server.pub >/dev/null 2>&1
    configdns >/dev/null 2>&1
    cat /dev/null >~/.bash_history && history -c
}
initslow() {
    [[ $(ss -lu | grep -wc '5300') != '0' ]] && {
        echo -e "\n${RED}[${CYAN}1${RED}] ${YELLOW}DETENER SLOWDNS${SCOLOR}"
        echo -e "${RED}[${CYAN}2${RED}] ${YELLOW}ELIMINAR SLOWDNS${SCOLOR}"
        echo -e "${RED}[${CYAN}3${RED}] ${YELLOW}VER INFORMACION${SCOLOR}"
        echo -e "${RED}[${CYAN}0${RED}] ${YELLOW}VOLVER${SCOLOR}"
        echo -ne "\n${GREEN}INGRESE UNA OPCION${SCOLOR}: "
        read op
        if [[ "$op" == '1' ]]; then
            screen -r -S "slow_dns" -X quit >/dev/null 2>&1
            screen -wipe >/dev/null 2>&1
            sed -i '/5300/d' /etc/autostart >/dev/null 2>&1
            sed -i '/slow_dns/d' /etc/SSHPlus/dns/autodns >/dev/null 2>&1
            echo -e "\n${RED}SLOWDNS DESACTIVADO!${SCOLOR}"
            sleep 2
            menu
        elif [[ "$op" == '2' ]]; then
            screen -r -S "slow_dns" -X quit >/dev/null 2>&1
            screen -wipe >/dev/null 2>&1
            sed -i '/5300/d' /etc/autostart >/dev/null 2>&1
            rm -rf /etc/SSHPlus/dns >/dev/null 2>&1
            echo -e "\n${RED}SLOWDNS ELIMINADO!${SCOLOR}"
            sleep 2
            menu
        elif [[ "$op" == '3' ]]; then
            [[ -e $DIR/server.pub ]] && keypub=$(cat $DIR/server.pub) || keypub='Nulo'
            [[ -e $DIR/autodns ]] && nameserver=$(grep -w 'server.key' /etc/SSHPlus/dns/autodns | awk -F' ' '{print $9}') || nameserver='Nulo'
            tmx='curl -sO https://raw.githubusercontent.com/Netxxus/SSHPLUS/main/Install/slowdns && chmod +x slowdns && ./slowdns'
            clear
            echo -e "${CORTITLE}           SSHPLUS SLOWDNS (Beta)            ${SCOLOR}"
            echo -e "\n${YELLOW}NAMESERVER(NS)${SCOLOR}: $nameserver"
            echo -e "${YELLOW}CLAVE PUBLICA${SCOLOR}: $keypub"
            echo -e "\n${GREEN}COMANDO TERMUX${SCOLOR}: ${tmx} ${nameserver} ${keypub}"
            echo -ne "\n${RED}ENTER${YELLOW} para volver al ${GREEN}MENU!${SCOLOR}"
            read
            menu
        elif [[ "$op" == '0' ]]; then
            sleep 1
            menu
        else
            echo -e "\n${RED}OPCION INVALIDA${SCOLOR}"
            sleep 1.5
            menu
        fi
    } || {
        clear
        echo -e "${CORTITLE}           SSHPLUS SLOWDNS (Beta)            ${SCOLOR}"
        echo -ne "\n${GREEN}INGRESE EL DOMINIO NS${SCOLOR}: "
        read ns
        [[ -z "$ns" ]] && {
            echo -e "\n${RED}DOMINIO INVALIDO${SCOLOR}"
            sleep 1.5
            initslow
        }
        echo -e "\n${RED}[${CYAN}1${RED}] ${YELLOW}SLOWDNS SSH${SCOLOR}"
        echo -e "${RED}[${CYAN}2${RED}] ${YELLOW}SLOWDNS SSL${SCOLOR}"
        echo -e "${RED}[${CYAN}3${RED}] ${YELLOW}SLOWDNS SSLH${SCOLOR}"
        echo -e "${RED}[${CYAN}4${RED}] ${YELLOW}SLOWDNS OPENVPN${SCOLOR}"
        echo -e "${RED}[${CYAN}0${RED}] ${YELLOW}VOLVER${SCOLOR}"
        echo -ne "\n${GREEN}INGRESE UNA OPCION${SCOLOR}: "
        read opcc
        if [[ "$opcc" == '1' ]]; then
            ptdns='22'
        elif [[ "$opcc" == '2' ]]; then
            ptdns=$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2)
            [[ $ptdns == '' ]] && {
                echo -e "\n${RED}PRIMERO INSTALE EL SSL TUNNEL!${SCOLOR}"
                sleep 1.5
                initslow
            }
        elif [[ "$opcc" == '3' ]]; then
            ptdns=$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2)
            [[ $ptdns == '' ]] && {
                echo -e "\n${RED}PRIMERO INSTALE EL SSLH!${SCOLOR}"
                sleep 1.5
                initslow
            }
        elif [[ "$opcc" == '4' ]]; then
            [[ ! -e /etc/openvpn/server.conf ]] && {
                echo -e "\n${RED}PRIMERO INSTALE EL OPENVPN!${SCOLOR}"
                sleep 1.5
                initslow
            } || {
                ptdns=$(sed -n 1p /etc/openvpn/server.conf| cut -d' ' -f2)
            }
        elif [[ "$opcc" == '0' ]]; then
            sleep 1.5
            menu
        else
            echo -e "\n${RED}OPCION INVALIDA${SCOLOR}"
            sleep 1.5
            initslow
        fi
        screen -dmS slow_dns $DIR/dns-server -udp :5300 -privkey-file $DIR/server.key ${ns} 0.0.0.0:${ptdns} >/dev/null 2>&1
        keypub=$(cat $DIR/server.pub)
        cd $HOME
        echo -e "\n${YELLOW}SLOWDNS ACTIVADO...${SCOLOR}"
        [[ ! -e /etc/iptables/rules.v4 ]] && {
            configdns > /dev/null 2>&1
            DEBIAN_FRONTEND=noninteractive apt install -y iptables-persistent >/dev/null 2>&1
        } || {
            sleep 2
            configdns > /dev/null 2>&1
            iptables-save > /etc/iptables/rules.v4
        }
        echo "screen -dmS slow_dns $DIR/dns-server -udp :5300 -privkey-file $DIR/server.key ${ns} 0.0.0.0:${ptdns}" >/etc/SSHPlus/dns/autodns
        chmod 777 /etc/SSHPlus/dns/autodns >/dev/null 2>&1
        echo "ss -lu|grep -w '5300' || /etc/SSHPlus/dns/autodns" >>/etc/autostart
        tmx='curl -sO https://raw.githubusercontent.com/Netxxus/SSHPLUS/main/Install/slowdns && chmod +x slowdns && ./slowdns'
        echo -e "\n${GREEN}SLOWDNS ACTIVADO!${SCOLOR}"
        echo -e "\n${YELLOW}COMANDO TERMUX${SCOLOR}: ${tmx} ${ns} ${keypub}"
        echo -ne "\n${RED}ENTER${YELLOW} para volver al ${GREEN}MENU!${SCOLOR}"
        read
        menu
    }
}
[[ -d $DIR ]] && {
    initslow
} || {
    installslowdns
    sleep 0.5
    initslow
}
