#!/bin/bash
fun_swap() {
    clear
		echo -e "\E[44;1;37m          GESTIONAR MEMORIA VIRTUAL             \E[0m"
        echo ""
		echo -e "\033[1;31mLa swap es un area de intercambio usada para aumentar la cantidad de memoria RAM \ndel sistema (RECOMENDADO PARA MAQUINAS CON POCA MEMORIA RAM).\033[0m"
        echo -e "\033[1;31mAntes de activar, verifique la cantidad de almacenamiento que tiene su maquina, \nsiempre deje almacenamiento de sobra para evitar bloqueos.\033[0m"
        echo ""
		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mACTIVAR SWAP / CAMBIAR VALOR DEL SWAP \033[0m"
		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mDESACTIVAR SWAP\033[0m"
		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLVER\033[0m"
		echo ""
		echo -ne "\033[1;32mQUE DESEA HACER \033[1;33m?\033[1;37m "
		read resposta
		if [[ "$resposta" = '1' ]]; then
            clear
			echo -e "\E[44;1;37m            MEMORIA VIRTUAL              \E[0m"
			echo ""
			echo -ne "\033[1;32mCUANTOS GIGAS DESEA UTILIZAR \033[1;33m?\033[1;37m: "
			read gigas
            [[ -z "$gigas" ]] && {
					echo ""
					echo -e "\033[1;31mGigas invalidas!"
					sleep 2
					clear
					menu
				}
            echo ""
			echo -e "\033[1;32mINICIANDO MEMORIA VIRTUAL \033[1;31m$gigas GB\033[1;33m"
			echo ""
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            fallocate -l ${gigas}G /bin/ram.img > /dev/null 2>&1
            chmod 600 /bin/ram.img > /dev/null 2>&1
            mkswap /bin/ram.img > /dev/null 2>&1
            swapon /bin/ram.img > /dev/null 2>&1
            echo 50  > /proc/sys/vm/swappiness
            echo '/bin/ram.img none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mMEMORIA VIRTUAL ACTIVADA CON EXITO\033[1;33m"
            sleep 2
			fun_swap
        elif [[ "$resposta" = '2' ]]; then
            clear
			echo -e "\E[44;1;37m          DESACTIVANDO MEMORIA VIRTUAL              \E[0m"
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mMEMORIA VIRTUAL DESACTIVADA CON EXITO!\033[1;33m"
			sleep 2
			fun_swap
        elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "\033[1;31mVolviendo...\033[0m"
			sleep 1
			menu
		else
			echo ""
			echo -e "\033[1;31mOpcion invalida!\033[0m"
			sleep 1
			fun_swap
		fi
}
fun_swap
